### ISSUE TITLE
Installation/import

### ISSUE THREAD

**Issue by julianpw** [mariaderrico/DPA#4]
For installation, I ran the `compile.sh` included, and the package will be installed (also confirmed by pip freeze) and the import works. However, after every reboot or opening a new console, this error appears when trying to import the package:

`ImportError: cannot import name '_PAk' from partially initialized module 'Pipeline' (most likely due to a circular import) (/home/julian/.pyenv/versions/3.8.6/lib/python3.8/site-packages/DPApipeline-0.0.2-py3.8.egg/Pipeline/__init__.py)`

This is regardless of whether I install it globally or in the venv, or even the console of the IDE. The only way to fix it that I've found is running the compile.sh script again, after which the import from that same console works normally again and I can use the package. What could the problem be?

**Comment by mariaderrico** [comment]
Thanks for pointing this out! The latest commit should solve the issue. 
Could you try it again and let me know if it is fine now?

**Comment by julianpw** [comment]
Now the import works okay, but it throws the another error when trying to fit:

`from Pipeline import DPA
import numpy as np

X = np.random.rand(10, 7)
est = DPA.DensityPeakAdvanced(Z=1.5)
est.fit_predict(X)`

The last line throws the error:

`Traceback (most recent call last):

  File "<ipython-input-5-5326d6cce989>", line 1, in <module>
    est.fit_predict(X)

  File "/home/julian/.local/share/virtualenvs/MD_analysis-QPVz01Kp/lib/python3.8/site-packages/DPApipeline-0.0.2-py3.8.egg/Pipeline/DPA.py", line 432, in fit_predict
    self.fit(X)

  File "/home/julian/.local/share/virtualenvs/MD_analysis-QPVz01Kp/lib/python3.8/site-packages/DPApipeline-0.0.2-py3.8.egg/Pipeline/DPA.py", line 392, in fit
    PAk = PointAdaptive_kNN(k_max=self.k_max_, D_thr=self.D_thr, metric=self.metric,

  File "/home/julian/.local/share/virtualenvs/MD_analysis-QPVz01Kp/lib/python3.8/site-packages/DPApipeline-0.0.2-py3.8.egg/Pipeline/PAk.py", line 278, in fit
    self.densities_, self.err_densities_, self.k_hat_, self.dc_ = _PointAdaptive_kNN(self.distances_,

  File "/home/julian/.local/share/virtualenvs/MD_analysis-QPVz01Kp/lib/python3.8/site-packages/DPApipeline-0.0.2-py3.8.egg/Pipeline/PAk.py", line 62, in _PointAdaptive_kNN
    from Pipeline import _PAk

ImportError: cannot import name '_PAk' from 'Pipeline' (/home/julian/.local/share/virtualenvs/MD_analysis-QPVz01Kp/lib/python3.8/site-packages/DPApipeline-0.0.2-py3.8.egg/Pipeline/__init__.py)`

(By the way, after a brief look in DPA.py it looks like something got swapped around in line 381:                `self.nn_distances_, nn_self.indices_ = nbrs.kneighbors(X)`; maybe it should be `self.nn_indices_?`)

**Comment by mariaderrico** [comment]
Hi, I have changed the install of Cython extensions and restructured the source code in the package (see commit above for more details). This should solve the latest error, could you try one more time?

**Comment by julianpw** [comment]
Now it seems to work well, also it does not give any warnings anymore during compilation (even though there is still this inversion in line 381, s.a.). Thank you!
